In [2]:
import pandas as pd
from pathlib import Path

# Ruta al archivo accidentes.csv
RUTA_ACCIDENTES = Path("../Datos/Raw/accidentes.csv")

# Leer el CSV
accidentes = pd.read_csv(RUTA_ACCIDENTES, parse_dates=["TW"])

# Mostrar primeras 5 filas
accidentes.head()

,TW,BARRIO,Lat,Lon,Dia_sem,Mes,Dia,Hora
0,2017-07-20 08:00:00,sandiego,6.233985,-75.570146,JUEVES,7,20,8
1,2017-06-15 16:00:00,lasacacias,6.238844,-75.600280,JUEVES,6,15,16
2,2017-07-02 16:00:00,lopezdemesa,6.285074,-75.584306,DOMINGO,7,2,16
3,2017-03-29 18:00:00,losconquistadores,6.239497,-75.583062,MIERCOLES,3,29,18
4,2017-07-26 20:00:00,cuartabrigada,6.260463,-75.590193,MIERCOLES,7,26,20

In [ ]:
print(len(accidentes))

120587

In [8]:
import pandas as pd
from pathlib import Path

# Ruta al archivo accidentes.csv
RUTA_ACCIDENTES = Path("../Datos/Staging/accidentes_staging.csv")

# Leer el CSV
accidentes_raw = pd.read_csv(RUTA_ACCIDENTES, parse_dates=["TW"])

# Mostrar primeras 5 filas
accidentes_raw.head()

C:\Users\camil\AppData\Local\Temp\ipykernel_10728\1512130413.py:8: DtypeWarning: Columns (0: RADICADO) have mixed types. Specify dtype option on import or set low_memory=False.
  accidentes_raw = pd.read_csv(RUTA_ACCIDENTES, parse_dates=["TW"])

,Lon,Lat,OBJECTID,RADICADO,HORA,Dia_sem,PERIODO,CLASE,DIRECCION,DIRECCION_ENC,...,GRAVEDAD,BARRIO,COMUNA,DISENO,Mes,Dia,FECHA,Hora_num,TW,Dia_Sem_REAL
0,-75.570146,6.233985,504352,1590356,08:00 AM,JUEVES,2017,CAIDA OCUPANTE,CR 43 A CL 33,CR 043 A 033 000 00000,...,HERIDO,sandiego,La Candelaria,Interseccion,7,20,2017-07-20,8,2017-07-20 08:00:00,JUEVES
1,-75.600280,6.238844,504353,1586285,04:50 PM,JUEVES,2017,CHOQUE,CR 80 CL 33,CR 080 033 000 00000,...,SOLO DAÑOS,lasacacias,Laureles Estadio,Glorieta,6,15,2017-06-15,16,2017-06-15 16:00:00,JUEVES
2,-75.584306,6.285074,504354,1588185,04:20 PM,DOMINGO,2017,CHOQUE,CR 80 CL 80 A,CR 080 080 A 000 00000,...,HERIDO,lopezdemesa,Robledo,Tramo de via,7,2,2017-07-02,16,2017-07-02 16:00:00,DOMINGO
3,-75.583062,6.239497,504355,1576853,06:29 PM,MIERCOLES,2017,CHOQUE,CL 33 Norte CR 65,CL 033 065 000 00000,...,SOLO DAÑOS,losconquistadores,Laureles Estadio,Tramo de via,3,29,2017-03-29,18,2017-03-29 18:00:00,MIERCOLES
4,-75.590193,6.260463,504356,1591283,08:10 PM,MIERCOLES,2017,ATROPELLO,CL 50 CR 74,CL 050 074 000 00000,...,HERIDO,cuartabrigada,Laureles Estadio,Tramo de via,7,26,2017-07-26,20,2017-07-26 20:00:00,MIERCOLES

In [9]:
print(len(accidentes_raw))

125122

In [10]:
print(len(accidentes_raw)-len(accidentes))

0